version: '3.8'

services:
  megafarma-api:
    build: .
    container_name: megafarma_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/app/config.json
